name: ci workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - uses: actions/checkout@v2
    - run:  bin/ipkg --version
    - run:  bin/ipkg update
    - run:  bin/ipkg install zlib

  install_via_homebrew:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run: brew tap leleliu008/fpliu
    - run: brew install ipkg
    - run: ipkg --version
    - run: ipkg update
    - run: ipkg install zlib
