name: ci workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11.0, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - run: export -p

    - if:   matrix.os == 'macos-11.0'
      run:  brew install gnu-sed

    - run:  brew install automake autoconf libtool pkg-config cmake meson gperf itstool tree lzip nasm doxygen protobuf xmlto

    - uses: actions/checkout@v2

    - run:  mv bin/ipkg $(brew --prefix)/bin

    - run:  ipkg version
    - run:  ipkg update
    - run:  ipkg install boost

  install:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11.0, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
    - name: install ipkg via homebrew
      run: |
        brew tap leleliu008/fpliu
        brew install ipkg

    - run: ipkg --version
