name: ci workflow

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  check_build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - uses: actions/checkout@v2

      - run: export -p

      - run: echo ${{ github.ref_name }}

      - run: bin/xcpkg --help
      - run: bin/xcpkg --version
      - run: bin/xcpkg --homedir
      - run: bin/xcpkg --homepage

      - run: bin/xcpkg env

      - run: bin/xcpkg integrate zsh

      - run: bin/xcpkg update

      - run: bin/xcpkg search lib
      - run: bin/xcpkg search zlib

      - run: bin/xcpkg info zlib
      - run: bin/xcpkg info zlib version
      - run: bin/xcpkg info zlib webpage

      - run: bin/xcpkg depends zlib
      - run: bin/xcpkg depends curl

      - run: bin/xcpkg homepage
      - run: bin/xcpkg homepage zlib

      - run: bin/xcpkg install zlib

      - run: bin/xcpkg info zlib
      - run: bin/xcpkg info zlib installed-dir
      - run: bin/xcpkg info zlib installed-metadata
      - run: bin/xcpkg info zlib installed-files
      - run: bin/xcpkg info zlib installed-abis
      - run: bin/xcpkg info zlib installed-datetime-unix
      - run: bin/xcpkg info zlib installed-datetime-formatted
      - run: bin/xcpkg info zlib installed-pkg-version

      - run: bin/xcpkg tree zlib
      - run: bin/xcpkg pack zlib

      - run: bin/xcpkg formula-repo list
      - run: bin/xcpkg formula view curl

      - run: bin/xcpkg target abis
      - run: bin/xcpkg target archs
      - run: bin/xcpkg target triples
      - run: bin/xcpkg target versions
      - run: bin/xcpkg target platforms

      - run: bin/xcpkg ls-available
      - run: bin/xcpkg ls-installed
      - run: bin/xcpkg ls-outdated

      - run: bin/xcpkg is-available zlib
      - run: bin/xcpkg is-installed zlib
      - run: bin/xcpkg is-outdated zlib || echo 'not outdated'

      - run: bin/xcpkg uninstall zlib

      - run: bin/xcpkg fetch curl

      - run: bin/xcpkg upgrade @self

  install_via_homebrew:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-10.15]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: brew tap leleliu008/fpliu
      - run: brew install xcpkg

      - run: xcpkg --help
      - run: xcpkg --version
      - run: xcpkg --homedir
      - run: xcpkg --homepage

      - run: xcpkg env

      - run: xcpkg integrate zsh

      - run: xcpkg update

      - run: xcpkg search lib
      - run: xcpkg search zlib

      - run: xcpkg info zlib
      - run: xcpkg info zlib version
      - run: xcpkg info zlib webpage

      - run: xcpkg depends zlib
      - run: xcpkg depends curl

      - run: xcpkg homepage
      - run: xcpkg homepage zlib

      - run: xcpkg install zlib

      - run: xcpkg info zlib
      - run: xcpkg info zlib installed-dir
      - run: xcpkg info zlib installed-metadata
      - run: xcpkg info zlib installed-files
      - run: xcpkg info zlib installed-abis
      - run: xcpkg info zlib installed-datetime-unix
      - run: xcpkg info zlib installed-datetime-formatted
      - run: xcpkg info zlib installed-pkg-version

      - run: xcpkg tree zlib
      - run: xcpkg pack zlib

      - run: xcpkg formula-repo list
      - run: xcpkg formula view curl

      - run: xcpkg target abis
      - run: xcpkg target archs
      - run: xcpkg target triples
      - run: xcpkg target versions
      - run: xcpkg target platforms

      - run: xcpkg ls-available
      - run: xcpkg ls-installed
      - run: xcpkg ls-outdated

      - run: xcpkg is-available zlib
      - run: xcpkg is-installed zlib
      - run: xcpkg is-outdated zlib || echo 'not outdated'

      - run: xcpkg uninstall zlib

      - run: xcpkg fetch curl

      - run: xcpkg upgrade @self
