name: ci workflow

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  check_build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - uses: actions/checkout@v3

      - run: export -p

      - run: echo ${{ github.ref_name }}

      - run: bin/xcpkg --help
      - run: bin/xcpkg --version

      - run: bin/xcpkg -h
      - run: bin/xcpkg -V

      - run: bin/xcpkg setup
      - run: bin/xcpkg env

      - run: bin/xcpkg integrate zsh

      - run: bin/xcpkg update

      - run: bin/xcpkg search lib
      - run: bin/xcpkg search zlib

      - run: bin/xcpkg info zlib
      - run: bin/xcpkg info zlib version
      - run: bin/xcpkg info zlib license

      - run: bin/xcpkg depends zlib
      - run: bin/xcpkg depends curl

      - run: bin/xcpkg install zlib --target=MacOSX/10.15/x86_64

      - run: bin/xcpkg info MacOSX/10.15/x86_64/zlib installed-dir
      - run: bin/xcpkg info MacOSX/10.15/x86_64/zlib installed-files
      - run: bin/xcpkg info MacOSX/10.15/x86_64/zlib installed-timestamp-unix
      - run: bin/xcpkg info MacOSX/10.15/x86_64/zlib installed-timestamp-iso-8601
      - run: bin/xcpkg info MacOSX/10.15/x86_64/zlib installed-pkg-version

      - run: bin/xcpkg tree MacOSX/10.15/x86_64/zlib
      - run: bin/xcpkg pack MacOSX/10.15/x86_64/zlib

      - run: bin/xcpkg formula-repo list
      - run: bin/xcpkg formula view curl

      - run: bin/xcpkg ls-target-archs
      - run: bin/xcpkg ls-target-archs MacOSX
      - run: bin/xcpkg ls-target-archs AppleTVOS
      - run: bin/xcpkg ls-target-archs AppleTVSimulator
      - run: bin/xcpkg ls-target-archs iPhoneOS
      - run: bin/xcpkg ls-target-archs iPhoneSimulator
      - run: bin/xcpkg ls-target-archs WatchOS
      - run: bin/xcpkg ls-target-archs WatchSimulator

      - run: bin/xcpkg ls-target-triples
      - run: bin/xcpkg ls-target-triples all
      - run: bin/xcpkg ls-target-triples 32bit
      - run: bin/xcpkg ls-target-triples 64bit

      - run: bin/xcpkg ls-target-versions
      - run: bin/xcpkg ls-target-versions MacOSX
      - run: bin/xcpkg ls-target-versions AppleTVOS
      - run: bin/xcpkg ls-target-versions AppleTVSimulator
      - run: bin/xcpkg ls-target-versions iPhoneOS
      - run: bin/xcpkg ls-target-versions iPhoneSimulator
      - run: bin/xcpkg ls-target-versions WatchOS
      - run: bin/xcpkg ls-target-versions WatchSimulator

      - run: bin/xcpkg ls-target-platforms

      - run: bin/xcpkg ls-available
      - run: bin/xcpkg ls-installed
      - run: bin/xcpkg ls-outdated

      - run: bin/xcpkg is-available MacOSX/10.15/x86_64/zlib
      - run: bin/xcpkg is-installed MacOSX/10.15/x86_64/zlib
      - run: bin/xcpkg is-outdated  MacOSX/10.15/x86_64/zlib || echo 'not outdated'

      - run: bin/xcpkg uninstall MacOSX/10.15/x86_64/zlib

      - run: bin/xcpkg fetch curl

      - run: bin/xcpkg upgrade-self

  install_via_homebrew:
    if: false
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    env:
      HOMEBREW_NO_INSTALL_CLEANUP: set

    steps:
      - run: brew tap leleliu008/fpliu
      - run: brew install xcpkg

      - run: xcpkg --help
      - run: xcpkg --version

      - run: xcpkg -h
      - run: xcpkg -V

      - run: xcpkg setup
      - run: xcpkg env

      - run: xcpkg integrate zsh

      - run: xcpkg update

      - run: xcpkg search lib
      - run: xcpkg search zlib

      - run: xcpkg info zlib
      - run: xcpkg info zlib version
      - run: xcpkg info zlib license

      - run: xcpkg depends zlib
      - run: xcpkg depends curl

      - run: xcpkg install zlib

      - run: xcpkg info zlib
      - run: xcpkg info zlib installed-dir
      - run: xcpkg info zlib installed-metadata
      - run: xcpkg info zlib installed-files
      - run: xcpkg info zlib installed-abis
      - run: xcpkg info zlib installed-datetime-unix
      - run: xcpkg info zlib installed-datetime-formatted
      - run: xcpkg info zlib installed-pkg-version

      - run: xcpkg tree zlib
      - run: xcpkg pack zlib

      - run: xcpkg formula-repo list
      - run: xcpkg formula view curl

      - run: xcpkg ls-target-abis
      - run: xcpkg ls-target-abis all
      - run: xcpkg ls-target-abis 32bit
      - run: xcpkg ls-target-abis 64bit

      - run: xcpkg ls-target-archs
      - run: xcpkg ls-target-archs MacOSX
      - run: xcpkg ls-target-archs AppleTVOS
      - run: xcpkg ls-target-archs AppleTVSimulator
      - run: xcpkg ls-target-archs iPhoneOS
      - run: xcpkg ls-target-archs iPhoneSimulator
      - run: xcpkg ls-target-archs WatchOS
      - run: xcpkg ls-target-archs WatchSimulator

      - run: xcpkg ls-target-triples
      - run: xcpkg ls-target-triples all
      - run: xcpkg ls-target-triples 32bit
      - run: xcpkg ls-target-triples 64bit

      - run: xcpkg ls-target-versions
      - run: xcpkg ls-target-versions MacOSX
      - run: xcpkg ls-target-versions AppleTVOS
      - run: xcpkg ls-target-versions AppleTVSimulator
      - run: xcpkg ls-target-versions iPhoneOS
      - run: xcpkg ls-target-versions iPhoneSimulator
      - run: xcpkg ls-target-versions WatchOS
      - run: xcpkg ls-target-versions WatchSimulator

      - run: xcpkg ls-target-platforms

      - run: xcpkg ls-available
      - run: xcpkg ls-installed
      - run: xcpkg ls-outdated

      - run: xcpkg is-available zlib
      - run: xcpkg is-installed zlib
      - run: xcpkg is-outdated zlib || echo 'not outdated'

      - run: xcpkg uninstall zlib

      - run: xcpkg fetch curl

      - run: xcpkg upgrade-self
