name: test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [macos-11, macos-12]
        target-platform: [ 'MacOSX/10.15/x86_64', 'MacOSX/11.0/x86_64', 'MacOSX/12.0/x86_64', 'MacOSX/13.0/x86_64', 'MacOSX/11.0/arm64', 'MacOSX/12.0/arm64', 'MacOSX/13.0/arm64' ]

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v3

      - run: export -p

      - run: echo ${{ github.ref_name }}

      - run: ./xcpkg --help
      - run: ./xcpkg -h

      - run: ./xcpkg --version
      - run: ./xcpkg -V

      - run: ./xcpkg gen-url-transform-sample

      - run: ./xcpkg env

      - run: ./xcpkg sysinfo

      - run: ./xcpkg xcinfo
      - run: ./xcpkg xcinfo --list-supported-platform-names

      - run: ./xcpkg setup

      - run: ./xcpkg integrate zsh

      - run: ./xcpkg update

      - run: ./xcpkg search lib
      - run: ./xcpkg search uctags


      - run: ./xcpkg info @all
      - run: ./xcpkg info uctags
      - run: ./xcpkg info uctags --yaml
      - run: ./xcpkg info uctags --json
      - run: ./xcpkg info uctags version
      - run: ./xcpkg info uctags license
      - run: ./xcpkg info uctags summary
      - run: ./xcpkg info uctags web-url
      - run: ./xcpkg info uctags git-url
      - run: ./xcpkg info uctags git-sha
      - run: ./xcpkg info uctags git-ref
      - run: ./xcpkg info uctags src-url
      - run: ./xcpkg info uctags src-sha


      - run: ./xcpkg formula uctags
      - run: ./xcpkg formula uctags --yaml
      - run: ./xcpkg formula uctags --json
      - run: ./xcpkg formula uctags version
      - run: ./xcpkg formula uctags license
      - run: ./xcpkg formula uctags summary
      - run: ./xcpkg formula uctags web-url
      - run: ./xcpkg formula uctags git-url
      - run: ./xcpkg formula uctags git-sha
      - run: ./xcpkg formula uctags git-ref
      - run: ./xcpkg formula uctags src-url
      - run: ./xcpkg formula uctags src-sha


      - run: ./xcpkg depends uctags
      - run: ./xcpkg depends uctags -t dot
      - run: ./xcpkg depends uctags -t box
      - run: ./xcpkg depends uctags -t dot -o a/
      - run: ./xcpkg depends uctags -o uctags.box


      - run: ./xcpkg install ${{ matrix.target-platform }}/uctags


      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags --yaml
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags --json
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags version
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags license
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags summary
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags web-url
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags git-url
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags git-sha
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags git-ref
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags src-url
      - run: ./xcpkg receipt ${{ matrix.target-platform }}/uctags src-sha


      - run: ./xcpkg info ${{ matrix.target-platform }}/uctags installed-dir
      - run: ./xcpkg info ${{ matrix.target-platform }}/uctags installed-files
      - run: ./xcpkg info ${{ matrix.target-platform }}/uctags installed-version
      - run: ./xcpkg info ${{ matrix.target-platform }}/uctags installed-timestamp-unix
      - run: ./xcpkg info ${{ matrix.target-platform }}/uctags installed-timestamp-iso-8601
      - run: ./xcpkg info ${{ matrix.target-platform }}/uctags installed-timestamp-rfc-3339
      - run: ./xcpkg info ${{ matrix.target-platform }}/uctags installed-timestamp-iso-8601-utc
      - run: ./xcpkg info ${{ matrix.target-platform }}/uctags installed-timestamp-rfc-3339-utc


      - run: ./xcpkg tree ${{ matrix.target-platform }}/uctags
      - run: ./xcpkg tree ${{ matrix.target-platform }}/uctags -a

      - run: ./xcpkg pack ${{ matrix.target-platform }}/uctags
      - run: ./xcpkg pack ${{ matrix.target-platform }}/uctags -t tar.gz
      - run: ./xcpkg pack ${{ matrix.target-platform }}/uctags -t tar.xz
      - run: ./xcpkg pack ${{ matrix.target-platform }}/uctags -t tar.xz -o .
      - run: ./xcpkg pack ${{ matrix.target-platform }}/uctags -o .
      - run: ./xcpkg pack ${{ matrix.target-platform }}/uctags -o xx.tar.xz

      - run: ./xcpkg formula-repo-list

      - run: ./xcpkg ls-available
      - run: ./xcpkg ls-installed
      - run: ./xcpkg ls-outdated

      - run: ./xcpkg is-available uctags
      - run: ./xcpkg is-installed ${{ matrix.target-platform }}/uctags
      - run: ./xcpkg is-outdated  ${{ matrix.target-platform }}/uctags || echo 'not outdated'

      - run: ./xcpkg uninstall ${{ matrix.target-platform }}/uctags

      - run: ./xcpkg fetch curl

      - run: ./xcpkg upgrade-self
