name: xcpkg-brew-version-compare

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  compare:

    runs-on: macos-12

    steps:
      - run: brew update
      - run: brew uninstall go@1.17
      - run: brew install --overwrite python@3.10 python@3.11

      - uses: actions/checkout@v3

      - run: ./xcpkg setup
      - run: ./xcpkg env
      - run: ./xcpkg update
      - run: BREW=/usr/local/bin/brew ./xcpkg compare-versions brew

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg
      - run: ./ppkg setup
      - run: PPKG=$PWD/ppkg ./xcpkg compare-versions ppkg
